/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.validation

import org.eclipse.xtext.validation.Check
import dk.sdu.mmmi.mdsd.math.MathExp
import dk.sdu.mmmi.mdsd.math.OneMath
import java.util.HashSet
import dk.sdu.mmmi.mdsd.math.MathPackage.Literals

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MathValidator extends AbstractMathValidator {
	
		HashSet<String> varibles = new HashSet();
		
		@Check
	def checkNoRepeatedGlobalVarDeclarions(MathExp mathExp) {
			
		for(OneMath math : mathExp.mathExp)
		{
			if(varibles.contains(math.name))
			{
				error("RepeatedGlobal Detected, fix it! ( ͠° ͟ʖ ͡°)=ε/̵͇̿̿/'̿̿ ̿ ̿ ̿ ̿ ̿", Literals.ONE_MATH__NAME)
                return
			}
			varibles.add(math.name)
		}
	}
	
	
}
