/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math.impl;

import dk.sdu.mmmi.mdsd.math.External;
import dk.sdu.mmmi.mdsd.math.MathPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>External</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.impl.ExternalImpl#getName <em>Name</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.impl.ExternalImpl#getArgumentLeft <em>Argument Left</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.impl.ExternalImpl#getArgumentsRight <em>Arguments Right</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExternalImpl extends MinimalEObjectImpl.Container implements External
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getArgumentLeft() <em>Argument Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArgumentLeft()
   * @generated
   * @ordered
   */
  protected static final String ARGUMENT_LEFT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getArgumentLeft() <em>Argument Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArgumentLeft()
   * @generated
   * @ordered
   */
  protected String argumentLeft = ARGUMENT_LEFT_EDEFAULT;

  /**
   * The cached value of the '{@link #getArgumentsRight() <em>Arguments Right</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArgumentsRight()
   * @generated
   * @ordered
   */
  protected EList<String> argumentsRight;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExternalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathPackage.Literals.EXTERNAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MathPackage.EXTERNAL__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getArgumentLeft()
  {
    return argumentLeft;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setArgumentLeft(String newArgumentLeft)
  {
    String oldArgumentLeft = argumentLeft;
    argumentLeft = newArgumentLeft;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MathPackage.EXTERNAL__ARGUMENT_LEFT, oldArgumentLeft, argumentLeft));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getArgumentsRight()
  {
    if (argumentsRight == null)
    {
      argumentsRight = new EDataTypeEList<String>(String.class, this, MathPackage.EXTERNAL__ARGUMENTS_RIGHT);
    }
    return argumentsRight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MathPackage.EXTERNAL__NAME:
        return getName();
      case MathPackage.EXTERNAL__ARGUMENT_LEFT:
        return getArgumentLeft();
      case MathPackage.EXTERNAL__ARGUMENTS_RIGHT:
        return getArgumentsRight();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MathPackage.EXTERNAL__NAME:
        setName((String)newValue);
        return;
      case MathPackage.EXTERNAL__ARGUMENT_LEFT:
        setArgumentLeft((String)newValue);
        return;
      case MathPackage.EXTERNAL__ARGUMENTS_RIGHT:
        getArgumentsRight().clear();
        getArgumentsRight().addAll((Collection<? extends String>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MathPackage.EXTERNAL__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MathPackage.EXTERNAL__ARGUMENT_LEFT:
        setArgumentLeft(ARGUMENT_LEFT_EDEFAULT);
        return;
      case MathPackage.EXTERNAL__ARGUMENTS_RIGHT:
        getArgumentsRight().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MathPackage.EXTERNAL__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MathPackage.EXTERNAL__ARGUMENT_LEFT:
        return ARGUMENT_LEFT_EDEFAULT == null ? argumentLeft != null : !ARGUMENT_LEFT_EDEFAULT.equals(argumentLeft);
      case MathPackage.EXTERNAL__ARGUMENTS_RIGHT:
        return argumentsRight != null && !argumentsRight.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", argumentLeft: ");
    result.append(argumentLeft);
    result.append(", argumentsRight: ");
    result.append(argumentsRight);
    result.append(')');
    return result.toString();
  }

} //ExternalImpl
