/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math.impl;

import dk.sdu.mmmi.mdsd.math.Expression;
import dk.sdu.mmmi.mdsd.math.ExternalUse;
import dk.sdu.mmmi.mdsd.math.MathPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>External Use</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.impl.ExternalUseImpl#getName <em>Name</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.impl.ExternalUseImpl#getArgumentLeft <em>Argument Left</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.impl.ExternalUseImpl#getArgumentsRight <em>Arguments Right</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExternalUseImpl extends ExpressionImpl implements ExternalUse
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getArgumentLeft() <em>Argument Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArgumentLeft()
   * @generated
   * @ordered
   */
  protected Expression argumentLeft;

  /**
   * The cached value of the '{@link #getArgumentsRight() <em>Arguments Right</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArgumentsRight()
   * @generated
   * @ordered
   */
  protected EList<Expression> argumentsRight;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExternalUseImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MathPackage.Literals.EXTERNAL_USE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MathPackage.EXTERNAL_USE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getArgumentLeft()
  {
    return argumentLeft;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetArgumentLeft(Expression newArgumentLeft, NotificationChain msgs)
  {
    Expression oldArgumentLeft = argumentLeft;
    argumentLeft = newArgumentLeft;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MathPackage.EXTERNAL_USE__ARGUMENT_LEFT, oldArgumentLeft, newArgumentLeft);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setArgumentLeft(Expression newArgumentLeft)
  {
    if (newArgumentLeft != argumentLeft)
    {
      NotificationChain msgs = null;
      if (argumentLeft != null)
        msgs = ((InternalEObject)argumentLeft).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MathPackage.EXTERNAL_USE__ARGUMENT_LEFT, null, msgs);
      if (newArgumentLeft != null)
        msgs = ((InternalEObject)newArgumentLeft).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MathPackage.EXTERNAL_USE__ARGUMENT_LEFT, null, msgs);
      msgs = basicSetArgumentLeft(newArgumentLeft, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MathPackage.EXTERNAL_USE__ARGUMENT_LEFT, newArgumentLeft, newArgumentLeft));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Expression> getArgumentsRight()
  {
    if (argumentsRight == null)
    {
      argumentsRight = new EObjectContainmentEList<Expression>(Expression.class, this, MathPackage.EXTERNAL_USE__ARGUMENTS_RIGHT);
    }
    return argumentsRight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MathPackage.EXTERNAL_USE__ARGUMENT_LEFT:
        return basicSetArgumentLeft(null, msgs);
      case MathPackage.EXTERNAL_USE__ARGUMENTS_RIGHT:
        return ((InternalEList<?>)getArgumentsRight()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MathPackage.EXTERNAL_USE__NAME:
        return getName();
      case MathPackage.EXTERNAL_USE__ARGUMENT_LEFT:
        return getArgumentLeft();
      case MathPackage.EXTERNAL_USE__ARGUMENTS_RIGHT:
        return getArgumentsRight();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MathPackage.EXTERNAL_USE__NAME:
        setName((String)newValue);
        return;
      case MathPackage.EXTERNAL_USE__ARGUMENT_LEFT:
        setArgumentLeft((Expression)newValue);
        return;
      case MathPackage.EXTERNAL_USE__ARGUMENTS_RIGHT:
        getArgumentsRight().clear();
        getArgumentsRight().addAll((Collection<? extends Expression>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MathPackage.EXTERNAL_USE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MathPackage.EXTERNAL_USE__ARGUMENT_LEFT:
        setArgumentLeft((Expression)null);
        return;
      case MathPackage.EXTERNAL_USE__ARGUMENTS_RIGHT:
        getArgumentsRight().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MathPackage.EXTERNAL_USE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MathPackage.EXTERNAL_USE__ARGUMENT_LEFT:
        return argumentLeft != null;
      case MathPackage.EXTERNAL_USE__ARGUMENTS_RIGHT:
        return argumentsRight != null && !argumentsRight.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ExternalUseImpl
