/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Let</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Let#getVar <em>Var</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Let#getBind <em>Bind</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.Let#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLet()
 * @model
 * @generated
 */
public interface Let extends Expression
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute.
   * @see #setVar(String)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLet_Var()
   * @model
   * @generated
   */
  String getVar();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Let#getVar <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' attribute.
   * @see #getVar()
   * @generated
   */
  void setVar(String value);

  /**
   * Returns the value of the '<em><b>Bind</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bind</em>' containment reference.
   * @see #setBind(Expression)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLet_Bind()
   * @model containment="true"
   * @generated
   */
  Expression getBind();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Let#getBind <em>Bind</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bind</em>' containment reference.
   * @see #getBind()
   * @generated
   */
  void setBind(Expression value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(Expression)
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getLet_Body()
   * @model containment="true"
   * @generated
   */
  Expression getBody();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.math.Let#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(Expression value);

} // Let
