/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.math.MathExp#getMathExp <em>Math Exp</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.math.MathPackage#getMathExp()
 * @model
 * @generated
 */
public interface MathExp extends EObject
{
  /**
   * Returns the value of the '<em><b>Math Exp</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.math.OneMath}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Math Exp</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.math.MathPackage#getMathExp_MathExp()
   * @model containment="true"
   * @generated
   */
  EList<OneMath> getMathExp();

} // MathExp
